// Generated by CoffeeScript 2.7.0
(function() {
  var bt, create, deldel, getLocal, inp, lista, root;

  root = document.getElementById('root');

  inp = document.getElementById('inp');

  bt = document.getElementById('bt');

  lista = [];

  getLocal = function() {
    var store;
    store = localStorage.cards;
    if (store) {
      return lista = [...JSON.parse(store)];
    } else {
      return localStorage.cards = "";
    }
  };

  deldel = function() {
    return console.log("asd");
  };

  create = function() {
    var btel, el, i, results;
    
    // clear inner
    root.innerHTML = "";
    results = [];
    for (i in lista) {
      el = document.createElement('div');
      el.innerText = lista[i];
      el.className = "card";
      btel = document.createElement('button');
      btel.dataset.id = i;
      btel.innerText = 'x';
      btel.addEventListener('click', function(e) {
        lista.splice(e.path[0].dataset.id, 1);
        localStorage.cards = JSON.stringify(lista);
        return create();
      });
      el.append(btel);
      root.append(el);
      results.push(inp.value = "");
    }
    return results;
  };

  getLocal();

  create();

  bt.onclick = function() {
    var val;
    val = inp.value.replace(/^\s+|\s+$/g, "");
    if (val !== '') {
      lista.unshift([val]);
      localStorage.cards = JSON.stringify(lista);
      return create();
    }
  };

}).call(this);
